### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by hakusaro** [MineBartekSA/TerraJump#1]
Hello!

I was looking at your code and realized you didn't have a license file. Can you [add one or clarify your license](http://choosealicense.com/)?

Thanks!

**Comment by MineBartekSA** [comment]
Sure i can! But i think i don't need any so why you sak?

**Comment by hakusaro** [comment]
Without a license it's implicitly all rights reserved. If this is your
intention you should add a note so people won't try to collaborate on your
work.

**Comment by MineBartekSA** [comment]
Ok i will add license but it's late so on thursday i add a license (i have loot of work (not coding))

**Comment by MineBartekSA** [comment]
I add a MIT License
