### ISSUE TITLE
Jump pads do not work & /TJ Edit Command Fails

### ISSUE THREAD

**Issue by TheBambino** [MineBartekSA/TerraJump#5]
Terraria Client: 1.4.1.2
TShock: 4.4.0 Pre-15
Database: Tried MySQL & sqlite
SSC: Enabled

**Jump Pads Do Not Work:**
As a first time user, to my understanding if a player has the correct group permission,`terrajump.use`, and steps on a jump pad tile, they should be launched to the specified config height. This is not the case. The specified tiles do nothing when walked over. The `/jump` command works fine. I assumed there was some type of setup considering the x,y columns in the TJPads table and users in the TJUsers database, so I could be missing a step in getting them to work. 

**Edit Tile Command Fails:**
Usage of `/tj e tile` or `/tj e tile xxx` produces a command failed error:
```
Command: ERROR: System.InvalidCastException: Specified cast is not valid.
   at TerraJump.TerraJump.<>c.<ChangeTile>b__23_2(FieldInfo t)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at TerraJump.TerraJump.ChangeTile(CommandArgs args)
   at TerraJump.TerraJump.Edit(CommandArgs args)
   at TerraJump.TerraJump.TerraJumpCommand(CommandArgs args)
   at TShockAPI.Command.Run(String msg, Boolean silent, TSPlayer ply, List`1 parms)
```

**Comment by MineBartekSA** [comment]
Thank you for your bug report!
I'm sorry that it took me 3 days, but I was busy.

I've fixed everything (hopefully)!
Jump pads worked for me. Make sure that the jump pad is correctly built and the user has the `terrajump.use` permission, or you had too new TShock version. 🤷
Command `/tj disable pad` did not work, but it is fixed now.
And finally, `/tj edit tile` command is now fixed.

Fixes are available from the 2.3.1 version of the plugin. You can find the link to the plugin on the [Pryaxis/Plugins](https://github.com/Pryaxis/plugins) repo (or in the pull requests of that repo).

**Comment by TheBambino** [comment]
That may have been my main issue then. What does a correctly built Jump Pad look like? I am using the default tile; Slime Blocks. There was an image on the old forums, but it's no longer visible. Thank you very much for the quick update!

**Comment by MineBartekSA** [comment]
![image](https://user-images.githubusercontent.com/19757593/106363847-53774100-632b-11eb-99ae-d9ecc5d9f153.png)
This is how a correctly build Jump Pad should look like

**Comment by aarvndhNG** [comment]
Hey can you make a README because i didn't how to use it @MineBartekSA
