### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by aarvndhNG** [MineBartekSA/TerraJump#6]
Can you please update this plugin to 1.4.4 terraria
@MineBartekSA

**Comment by MineBartekSA** [comment]
Hi!
I'm glad to see that someone is still interested in my plugin!
I'll update it asap, although I'll try to finish by tomorrow.

**Comment by aarvndhNG** [comment]
> Hi! I'm glad to see that someone is still interested in my plugin! I'll update it asap, although I'll try to finish by tomorrow.

Thanks so much if you don't mind can you update this plugin UserSpecificFunctions

**Comment by aarvndhNG** [comment]
@MineBartekSA

**Comment by MineBartekSA** [comment]
Although I have pretty much finished updating this plugin, the key part is missing.
The hook I've been using to detect that a player has triggered a pressure plate does not work.
There is some bug in the latest versions of OTAPI that broke this hook.

I could just finish updating the plugin right now, but no jump pad would work.

While I wait for this [issue](https://github.com/SignatureBeef/Open-Terraria-API/issues/104) to be resolved, I'll try looking into it myself.

And for the UserSpecificFunctions plugin, I won't make any promises, but if I'll feel like it, I might update it. If I can find the code for it.

**Comment by aarvndhNG** [comment]
> Although I have pretty much finished updating this plugin, the key part is missing. The hook I've been using to detect that a player has triggered a pressure plate does not work. There is some bug in the latest versions of OTAPI that broke this hook.
> 
> I could just finish updating the plugin right now, but no jump pad would work.
> 
> While I wait for this [issue](https://github.com/SignatureBeef/Open-Terraria-API/issues/104) to be resolved, I'll try looking into it myself.
> 
> And for the UserSpecificFunctions plugin, I won't make any promises, but if I'll feel like it, I might update it. If I can find the code for it.

Thanks so much bro

**Comment by aarvndhNG** [comment]
Thanks so much @MineBartekSA bro

**Comment by aarvndhNG** [comment]
If you don't mind can you update the UserSpecificFunctions plugin because i really need that plugin so please @MineBartekSA

**Comment by MineBartekSA** [comment]
Firstly, I finally updated TerraJump.
You can download it from the [release](https://github.com/MineBartekSA/TerraJump/releases) page of this repository, or you can wait for it to be verified and updated on the [official plugin list](https://github.com/Pryaxis/Plugins)

Secondly, please don't bother people on the internet to do things for you for free.
I'll gladly update `UserSpecificFunctions` on the spot if you'll offer some compensation.
This is quite a massive plugin that needs to be ported, updated and then tested throughout—a lot of unpaid work.
I might or not update this plugin for fun. If you want, you can wait and see. No promises!
